const test = require("node:test");
const assert = require("node:assert/strict");
const {
  escapeHtml,
  buildQuotationPdfHtml,
  buildInvoicePdfHtml,
  buildPaymentReceiptPdfHtml,
} = require("../src/pdfHtml.js");

test("escapeHtml escapes special characters", () => {
  assert.equal(escapeHtml(`<&>"`), "&lt;&amp;&gt;&quot;");
});

test("buildQuotationPdfHtml uses client-facing quotation structure", () => {
  const html = buildQuotationPdfHtml({
    companyName: 'Acme <Ltd>',
    companyAddress: "Line 1\nLine 2",
    companyPhone: "+256",
    opportunityName: "Job A",
    client: { name: "Client & Co", phone: "1", email: "a@b.c", typeLabel: "Client", notes: "Note" },
    quotationRef: "qid-12345",
    status: "draft",
    createdAtStr: "Jan 1, 2026",
    lines: [{ description: "Line & co", quantity: 1, unit_price: 100 }],
    subTotal: 100,
    taxAmount: 18,
    totalAmount: 118,
  });
  assert.match(html, /Acme &lt;Ltd&gt;/);
  assert.match(html, /Line &amp; co/);
  assert.match(html, /QUOTATION/);
  assert.match(html, /Service offer/);
  assert.match(html, /Total cost/);
  assert.doesNotMatch(html, /Scope of work/);
  assert.match(html, /Terms and acceptance/);
  assert.match(html, /Quotation #/);
  assert.match(html, /Quotation valid until/);
  assert.match(html, /TOTAL:/);
  assert.doesNotMatch(html, /Project summary/);
  assert.match(html, /Job A/);
  assert.match(html, /Prepared for/);
  assert.match(html, /Client &amp; Co/);
  assert.doesNotMatch(html, /Full quotation reference/);
  assert.doesNotMatch(html, /Generated by ServOps/);
  assert.doesNotMatch(html, /<script/i);
});

test("buildQuotationPdfHtml omits VAT row when includeVat is false", () => {
  const html = buildQuotationPdfHtml({
    companyName: null,
    opportunityName: "Job",
    clientName: null,
    quotationRef: "qid-999",
    status: "draft",
    createdAtStr: null,
    lines: [],
    subTotal: 100,
    taxAmount: 0,
    totalAmount: 100,
    includeVat: false,
  });
  assert.doesNotMatch(html, /VAT \(18%\)/);
});

test("buildInvoicePdfHtml prioritizes invoice identity and payment summary", () => {
  const html = buildInvoicePdfHtml({
    business: {
      companyName: "Acme Co",
      companyAddress: "Kampala",
      companyPhone: "+256",
    },
    client: { name: "Jane", phone: "1", email: "j@x.com", typeLabel: "Client", notes: "VIP" },
    project: {
      name: "Build A",
      status: "active",
      budgetLabel: "UGX 1,000,000",
      opportunityName: "Opp X",
      retainerSummary: "UGX 0 balance · UGX 10,000 total",
    },
    invoiceRef: "inv-full-uuid-here",
    invoiceStatus: "issued",
    issuedDateStr: "Jan 1",
    dueDateStr: "Jan 15",
    updatedAtStr: "Jan 2",
    taxRateLabel: "18%",
    amountPaidStr: "UGX 0",
    balanceDueStr: "UGX 118,000",
    paymentsCount: 0,
    lines: [{ description: "Work", quantity: 1, unit_price: 100 }],
    subTotal: 100,
    taxAmount: 18,
    totalAmount: 118,
    includeVat: true,
    currencyCode: "UGX",
  });
  assert.match(html, /Header/);
  assert.match(html, /Invoice #inv-full/);
  assert.match(html, /Bill to/);
  assert.match(html, /Billing details/);
  assert.match(html, /Payment summary/);
  assert.match(html, /Amount paid/);
  assert.match(html, /Balance due/);
  assert.doesNotMatch(html, /Project prospect/);
  assert.doesNotMatch(html, /Full reference number/);
  assert.match(html, /Acme Co/);
  assert.match(html, /Jane/);
  assert.match(html, /Build A/);
  assert.doesNotMatch(html, /<script/i);
});

test("buildPaymentReceiptPdfHtml highlights payment and simplifies receipt details", () => {
  const html = buildPaymentReceiptPdfHtml({
    business: { companyName: "Acme Co", companyAddress: "Kampala", companyPhone: "+256" },
    client: { name: "Jane", phone: "1", email: "j@x.com", typeLabel: "Client", notes: "VIP" },
    project: {
      name: "Build A",
      status: "active",
      opportunityName: "Opp X",
      opportunityLocation: "Nansana",
      opportunityContactName: "John",
    },
    receiptRef: "rec-full-uuid-here",
    paymentRef: "pay-full-uuid-here",
    invoiceRef: "inv-full-uuid-here",
    invoiceStatus: "issued",
    receiptDateStr: "Jan 2",
    paymentDateStr: "Jan 1",
    paymentMethod: "momo",
    paymentAmount: 100,
    invoiceTotalStr: "UGX 118,000",
    outstandingInvoiceStr: "UGX 18,000",
    outstandingOverallStr: "UGX 200,000",
    thankYouNote: "Thank you for your trust.",
    currencyCode: "UGX",
  });

  assert.match(html, /RECEIPT/);
  assert.match(html, /Amount Received/);
  assert.match(html, /UGX 100/);
  assert.match(html, /Payment date/);
  assert.match(html, /Payment method/);
  assert.match(html, /Business/);
  assert.match(html, /Client/);
  assert.match(html, /Description/);
  assert.match(html, /References/);
  assert.match(html, /Balance summary/);
  assert.match(html, /Acknowledgment/);
  assert.match(html, /…rec-full/);
  assert.match(html, /Invoice total/);
  assert.match(html, /Balance remaining/);
  assert.doesNotMatch(html, /Project prospect/);
  assert.doesNotMatch(html, /Full receipt reference/);
  assert.doesNotMatch(html, /Generated by ServOps/);
  assert.doesNotMatch(html, /<script/i);
});
